### ISSUE TITLE
Delete this jmeter-analysis-gradle-plugin

### ISSUE THREAD

**Issue by djangofan** [jmeter-gradle-plugin/jmeter-analysis-gradle-plugin#1]
Delete this jmeter-analysis-gradle-plugin

Jmeter 3.x has improved support around this and so I don't think there is any need to support the old jmeter-analysis plugin any more.

**Comment by foragerr** [comment]
Agreed. Considering I haven't done anything with this in over a year, it is unlikely i'll make any significant contributions here anyway.
